//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 26-Jan-16 16:07:38
namespace WebApplication1.AdventureWorks_WcfDataService
{
    
    /// <summary>
    /// There are no comments for AdventureWorksEntities in the schema.
    /// </summary>
    public partial class AdventureWorksEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new AdventureWorksEntities object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public AdventureWorksEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "AdventureWorksModel", "WebApplication1.AdventureWorks_WcfDataService");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("WebApplication1.AdventureWorks_WcfDataService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("AdventureWorksModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Customers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Customer> Customers
        {
            get
            {
                if ((this._Customers == null))
                {
                    this._Customers = base.CreateQuery<Customer>("Customers");
                }
                return this._Customers;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Customer> _Customers;
        /// <summary>
        /// There are no comments for SalesOrderDetails in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<SalesOrderDetail> SalesOrderDetails
        {
            get
            {
                if ((this._SalesOrderDetails == null))
                {
                    this._SalesOrderDetails = base.CreateQuery<SalesOrderDetail>("SalesOrderDetails");
                }
                return this._SalesOrderDetails;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<SalesOrderDetail> _SalesOrderDetails;
        /// <summary>
        /// There are no comments for SalesOrderHeaders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<SalesOrderHeader> SalesOrderHeaders
        {
            get
            {
                if ((this._SalesOrderHeaders == null))
                {
                    this._SalesOrderHeaders = base.CreateQuery<SalesOrderHeader>("SalesOrderHeaders");
                }
                return this._SalesOrderHeaders;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<SalesOrderHeader> _SalesOrderHeaders;
        /// <summary>
        /// There are no comments for Customers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCustomers(Customer customer)
        {
            base.AddObject("Customers", customer);
        }
        /// <summary>
        /// There are no comments for SalesOrderDetails in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSalesOrderDetails(SalesOrderDetail salesOrderDetail)
        {
            base.AddObject("SalesOrderDetails", salesOrderDetail);
        }
        /// <summary>
        /// There are no comments for SalesOrderHeaders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSalesOrderHeaders(SalesOrderHeader salesOrderHeader)
        {
            base.AddObject("SalesOrderHeaders", salesOrderHeader);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"AdventureWorksModel\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/" +
                "edm\"><EntityType Name=\"Customer\"><Key><PropertyRef Name=\"CustomerID\" /></Key><Pr" +
                "operty Name=\"CustomerID\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPatt" +
                "ern=\"Identity\" xmlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation" +
                "\" /><Property Name=\"NameStyle\" Type=\"Edm.Boolean\" Nullable=\"false\" /><Property N" +
                "ame=\"Title\" Type=\"Edm.String\" MaxLength=\"8\" FixedLength=\"false\" Unicode=\"true\" /" +
                "><Property Name=\"FirstName\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"50\" Fi" +
                "xedLength=\"false\" Unicode=\"true\" /><Property Name=\"MiddleName\" Type=\"Edm.String\"" +
                " MaxLength=\"50\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"LastName\" T" +
                "ype=\"Edm.String\" Nullable=\"false\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"tr" +
                "ue\" /><Property Name=\"Suffix\" Type=\"Edm.String\" MaxLength=\"10\" FixedLength=\"fals" +
                "e\" Unicode=\"true\" /><Property Name=\"CompanyName\" Type=\"Edm.String\" MaxLength=\"12" +
                "8\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"SalesPerson\" Type=\"Edm.S" +
                "tring\" MaxLength=\"256\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Emai" +
                "lAddress\" Type=\"Edm.String\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"true\" />" +
                "<Property Name=\"Phone\" Type=\"Edm.String\" MaxLength=\"25\" FixedLength=\"false\" Unic" +
                "ode=\"true\" /><Property Name=\"PasswordHash\" Type=\"Edm.String\" Nullable=\"false\" Ma" +
                "xLength=\"128\" FixedLength=\"false\" Unicode=\"false\" /><Property Name=\"PasswordSalt" +
                "\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"10\" FixedLength=\"false\" Unicode=" +
                "\"false\" /><Property Name=\"rowguid\" Type=\"Edm.Guid\" Nullable=\"false\" /><Property " +
                "Name=\"ModifiedDate\" Type=\"Edm.DateTime\" Nullable=\"false\" Precision=\"3\" /><Naviga" +
                "tionProperty Name=\"SalesOrderHeaders\" Relationship=\"AdventureWorksModel.FK_Sales" +
                "OrderHeader_Customer_CustomerID\" ToRole=\"SalesOrderHeader\" FromRole=\"Customer\" /" +
                "></EntityType><EntityType Name=\"SalesOrderDetail\"><Key><PropertyRef Name=\"SalesO" +
                "rderDetailID\" /><PropertyRef Name=\"SalesOrderID\" /></Key><Property Name=\"SalesOr" +
                "derID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"SalesOrderDetailID\" T" +
                "ype=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"h" +
                "ttp://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"OrderQ" +
                "ty\" Type=\"Edm.Int16\" Nullable=\"false\" /><Property Name=\"ProductID\" Type=\"Edm.Int" +
                "32\" Nullable=\"false\" /><Property Name=\"UnitPrice\" Type=\"Edm.Decimal\" Nullable=\"f" +
                "alse\" Precision=\"19\" Scale=\"4\" /><Property Name=\"UnitPriceDiscount\" Type=\"Edm.De" +
                "cimal\" Nullable=\"false\" Precision=\"19\" Scale=\"4\" /><Property Name=\"LineTotal\" Ty" +
                "pe=\"Edm.Decimal\" Nullable=\"false\" Precision=\"38\" Scale=\"6\" p6:StoreGeneratedPatt" +
                "ern=\"Computed\" xmlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation" +
                "\" /><Property Name=\"rowguid\" Type=\"Edm.Guid\" Nullable=\"false\" /><Property Name=\"" +
                "ModifiedDate\" Type=\"Edm.DateTime\" Nullable=\"false\" Precision=\"3\" /><NavigationPr" +
                "operty Name=\"SalesOrderHeader\" Relationship=\"AdventureWorksModel.FK_SalesOrderDe" +
                "tail_SalesOrderHeader_SalesOrderID\" ToRole=\"SalesOrderHeader\" FromRole=\"SalesOrd" +
                "erDetail\" /></EntityType><EntityType Name=\"SalesOrderHeader\"><Key><PropertyRef N" +
                "ame=\"SalesOrderID\" /></Key><Property Name=\"SalesOrderID\" Type=\"Edm.Int32\" Nullab" +
                "le=\"false\" /><Property Name=\"RevisionNumber\" Type=\"Edm.Byte\" Nullable=\"false\" />" +
                "<Property Name=\"OrderDate\" Type=\"Edm.DateTime\" Nullable=\"false\" Precision=\"3\" />" +
                "<Property Name=\"DueDate\" Type=\"Edm.DateTime\" Nullable=\"false\" Precision=\"3\" /><P" +
                "roperty Name=\"ShipDate\" Type=\"Edm.DateTime\" Precision=\"3\" /><Property Name=\"Stat" +
                "us\" Type=\"Edm.Byte\" Nullable=\"false\" /><Property Name=\"OnlineOrderFlag\" Type=\"Ed" +
                "m.Boolean\" Nullable=\"false\" /><Property Name=\"SalesOrderNumber\" Type=\"Edm.String" +
                "\" Nullable=\"false\" MaxLength=\"25\" FixedLength=\"false\" Unicode=\"true\" p6:StoreGen" +
                "eratedPattern=\"Computed\" xmlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/" +
                "annotation\" /><Property Name=\"PurchaseOrderNumber\" Type=\"Edm.String\" MaxLength=\"" +
                "25\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"AccountNumber\" Type=\"Ed" +
                "m.String\" MaxLength=\"15\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Cu" +
                "stomerID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"ShipToAddressID\" T" +
                "ype=\"Edm.Int32\" /><Property Name=\"BillToAddressID\" Type=\"Edm.Int32\" /><Property " +
                "Name=\"ShipMethod\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"50\" FixedLength=" +
                "\"false\" Unicode=\"true\" /><Property Name=\"CreditCardApprovalCode\" Type=\"Edm.Strin" +
                "g\" MaxLength=\"15\" FixedLength=\"false\" Unicode=\"false\" /><Property Name=\"SubTotal" +
                "\" Type=\"Edm.Decimal\" Nullable=\"false\" Precision=\"19\" Scale=\"4\" /><Property Name=" +
                "\"TaxAmt\" Type=\"Edm.Decimal\" Nullable=\"false\" Precision=\"19\" Scale=\"4\" /><Propert" +
                "y Name=\"Freight\" Type=\"Edm.Decimal\" Nullable=\"false\" Precision=\"19\" Scale=\"4\" />" +
                "<Property Name=\"TotalDue\" Type=\"Edm.Decimal\" Nullable=\"false\" Precision=\"19\" Sca" +
                "le=\"4\" p6:StoreGeneratedPattern=\"Computed\" xmlns:p6=\"http://schemas.microsoft.co" +
                "m/ado/2009/02/edm/annotation\" /><Property Name=\"Comment\" Type=\"Edm.String\" MaxLe" +
                "ngth=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"rowguid\" Type=\"E" +
                "dm.Guid\" Nullable=\"false\" /><Property Name=\"ModifiedDate\" Type=\"Edm.DateTime\" Nu" +
                "llable=\"false\" Precision=\"3\" /><NavigationProperty Name=\"Customer\" Relationship=" +
                "\"AdventureWorksModel.FK_SalesOrderHeader_Customer_CustomerID\" ToRole=\"Customer\" " +
                "FromRole=\"SalesOrderHeader\" /><NavigationProperty Name=\"SalesOrderDetails\" Relat" +
                "ionship=\"AdventureWorksModel.FK_SalesOrderDetail_SalesOrderHeader_SalesOrderID\" " +
                "ToRole=\"SalesOrderDetail\" FromRole=\"SalesOrderHeader\" /></EntityType><Associatio" +
                "n Name=\"FK_SalesOrderHeader_Customer_CustomerID\"><End Type=\"AdventureWorksModel." +
                "Customer\" Role=\"Customer\" Multiplicity=\"1\" /><End Type=\"AdventureWorksModel.Sale" +
                "sOrderHeader\" Role=\"SalesOrderHeader\" Multiplicity=\"*\" /><ReferentialConstraint>" +
                "<Principal Role=\"Customer\"><PropertyRef Name=\"CustomerID\" /></Principal><Depende" +
                "nt Role=\"SalesOrderHeader\"><PropertyRef Name=\"CustomerID\" /></Dependent></Refere" +
                "ntialConstraint></Association><Association Name=\"FK_SalesOrderDetail_SalesOrderH" +
                "eader_SalesOrderID\"><End Type=\"AdventureWorksModel.SalesOrderHeader\" Role=\"Sales" +
                "OrderHeader\" Multiplicity=\"1\"><OnDelete Action=\"Cascade\" /></End><End Type=\"Adve" +
                "ntureWorksModel.SalesOrderDetail\" Role=\"SalesOrderDetail\" Multiplicity=\"*\" /><Re" +
                "ferentialConstraint><Principal Role=\"SalesOrderHeader\"><PropertyRef Name=\"SalesO" +
                "rderID\" /></Principal><Dependent Role=\"SalesOrderDetail\"><PropertyRef Name=\"Sale" +
                "sOrderID\" /></Dependent></ReferentialConstraint></Association></Schema><Schema N" +
                "amespace=\"Data.AdventureWorks\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/e" +
                "dm\"><EntityContainer Name=\"AdventureWorksEntities\" m:IsDefaultEntityContainer=\"t" +
                "rue\"><EntitySet Name=\"Customers\" EntityType=\"AdventureWorksModel.Customer\" /><En" +
                "titySet Name=\"SalesOrderDetails\" EntityType=\"AdventureWorksModel.SalesOrderDetai" +
                "l\" /><EntitySet Name=\"SalesOrderHeaders\" EntityType=\"AdventureWorksModel.SalesOr" +
                "derHeader\" /><AssociationSet Name=\"FK_SalesOrderHeader_Customer_CustomerID\" Asso" +
                "ciation=\"AdventureWorksModel.FK_SalesOrderHeader_Customer_CustomerID\"><End Role=" +
                "\"Customer\" EntitySet=\"Customers\" /><End Role=\"SalesOrderHeader\" EntitySet=\"Sales" +
                "OrderHeaders\" /></AssociationSet><AssociationSet Name=\"FK_SalesOrderDetail_Sales" +
                "OrderHeader_SalesOrderID\" Association=\"AdventureWorksModel.";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart1 = "FK_SalesOrderDetail_SalesOrderHeader_SalesOrderID\"><End Role=\"SalesOrderDetail\" E" +
                "ntitySet=\"SalesOrderDetails\" /><End Role=\"SalesOrderHeader\" EntitySet=\"SalesOrde" +
                "rHeaders\" /></AssociationSet></EntityContainer></Schema></edmx:DataServices></ed" +
                "mx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0, ModelPart1);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for AdventureWorksModel.Customer in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CustomerID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("CustomerID")]
    public partial class Customer
    {
        /// <summary>
        /// Create a new Customer object.
        /// </summary>
        /// <param name="customerID">Initial value of CustomerID.</param>
        /// <param name="nameStyle">Initial value of NameStyle.</param>
        /// <param name="firstName">Initial value of FirstName.</param>
        /// <param name="lastName">Initial value of LastName.</param>
        /// <param name="passwordHash">Initial value of PasswordHash.</param>
        /// <param name="passwordSalt">Initial value of PasswordSalt.</param>
        /// <param name="rowguid">Initial value of rowguid.</param>
        /// <param name="modifiedDate">Initial value of ModifiedDate.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Customer CreateCustomer(int customerID, bool nameStyle, string firstName, string lastName, string passwordHash, string passwordSalt, global::System.Guid rowguid, global::System.DateTime modifiedDate)
        {
            Customer customer = new Customer();
            customer.CustomerID = customerID;
            customer.NameStyle = nameStyle;
            customer.FirstName = firstName;
            customer.LastName = lastName;
            customer.PasswordHash = passwordHash;
            customer.PasswordSalt = passwordSalt;
            customer.rowguid = rowguid;
            customer.ModifiedDate = modifiedDate;
            return customer;
        }
        /// <summary>
        /// There are no comments for Property CustomerID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CustomerID
        {
            get
            {
                return this._CustomerID;
            }
            set
            {
                this.OnCustomerIDChanging(value);
                this._CustomerID = value;
                this.OnCustomerIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CustomerID;
        partial void OnCustomerIDChanging(int value);
        partial void OnCustomerIDChanged();
        /// <summary>
        /// There are no comments for Property NameStyle in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool NameStyle
        {
            get
            {
                return this._NameStyle;
            }
            set
            {
                this.OnNameStyleChanging(value);
                this._NameStyle = value;
                this.OnNameStyleChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _NameStyle;
        partial void OnNameStyleChanging(bool value);
        partial void OnNameStyleChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property MiddleName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MiddleName
        {
            get
            {
                return this._MiddleName;
            }
            set
            {
                this.OnMiddleNameChanging(value);
                this._MiddleName = value;
                this.OnMiddleNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MiddleName;
        partial void OnMiddleNameChanging(string value);
        partial void OnMiddleNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this._LastName = value;
                this.OnLastNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property Suffix in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Suffix
        {
            get
            {
                return this._Suffix;
            }
            set
            {
                this.OnSuffixChanging(value);
                this._Suffix = value;
                this.OnSuffixChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Suffix;
        partial void OnSuffixChanging(string value);
        partial void OnSuffixChanged();
        /// <summary>
        /// There are no comments for Property CompanyName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CompanyName
        {
            get
            {
                return this._CompanyName;
            }
            set
            {
                this.OnCompanyNameChanging(value);
                this._CompanyName = value;
                this.OnCompanyNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CompanyName;
        partial void OnCompanyNameChanging(string value);
        partial void OnCompanyNameChanged();
        /// <summary>
        /// There are no comments for Property SalesPerson in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SalesPerson
        {
            get
            {
                return this._SalesPerson;
            }
            set
            {
                this.OnSalesPersonChanging(value);
                this._SalesPerson = value;
                this.OnSalesPersonChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SalesPerson;
        partial void OnSalesPersonChanging(string value);
        partial void OnSalesPersonChanged();
        /// <summary>
        /// There are no comments for Property EmailAddress in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string EmailAddress
        {
            get
            {
                return this._EmailAddress;
            }
            set
            {
                this.OnEmailAddressChanging(value);
                this._EmailAddress = value;
                this.OnEmailAddressChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _EmailAddress;
        partial void OnEmailAddressChanging(string value);
        partial void OnEmailAddressChanged();
        /// <summary>
        /// There are no comments for Property Phone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Phone
        {
            get
            {
                return this._Phone;
            }
            set
            {
                this.OnPhoneChanging(value);
                this._Phone = value;
                this.OnPhoneChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Phone;
        partial void OnPhoneChanging(string value);
        partial void OnPhoneChanged();
        /// <summary>
        /// There are no comments for Property PasswordHash in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PasswordHash
        {
            get
            {
                return this._PasswordHash;
            }
            set
            {
                this.OnPasswordHashChanging(value);
                this._PasswordHash = value;
                this.OnPasswordHashChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PasswordHash;
        partial void OnPasswordHashChanging(string value);
        partial void OnPasswordHashChanged();
        /// <summary>
        /// There are no comments for Property PasswordSalt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PasswordSalt
        {
            get
            {
                return this._PasswordSalt;
            }
            set
            {
                this.OnPasswordSaltChanging(value);
                this._PasswordSalt = value;
                this.OnPasswordSaltChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PasswordSalt;
        partial void OnPasswordSaltChanging(string value);
        partial void OnPasswordSaltChanged();
        /// <summary>
        /// There are no comments for Property rowguid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid rowguid
        {
            get
            {
                return this._rowguid;
            }
            set
            {
                this.OnrowguidChanging(value);
                this._rowguid = value;
                this.OnrowguidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _rowguid;
        partial void OnrowguidChanging(global::System.Guid value);
        partial void OnrowguidChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this._ModifiedDate = value;
                this.OnModifiedDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for SalesOrderHeaders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<SalesOrderHeader> SalesOrderHeaders
        {
            get
            {
                return this._SalesOrderHeaders;
            }
            set
            {
                if ((value != null))
                {
                    this._SalesOrderHeaders = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<SalesOrderHeader> _SalesOrderHeaders = new global::System.Collections.ObjectModel.Collection<SalesOrderHeader>();
    }
    /// <summary>
    /// There are no comments for AdventureWorksModel.SalesOrderDetail in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SalesOrderDetailID
    /// SalesOrderID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("SalesOrderDetailID", "SalesOrderID")]
    public partial class SalesOrderDetail
    {
        /// <summary>
        /// Create a new SalesOrderDetail object.
        /// </summary>
        /// <param name="salesOrderID">Initial value of SalesOrderID.</param>
        /// <param name="salesOrderDetailID">Initial value of SalesOrderDetailID.</param>
        /// <param name="orderQty">Initial value of OrderQty.</param>
        /// <param name="productID">Initial value of ProductID.</param>
        /// <param name="unitPrice">Initial value of UnitPrice.</param>
        /// <param name="unitPriceDiscount">Initial value of UnitPriceDiscount.</param>
        /// <param name="lineTotal">Initial value of LineTotal.</param>
        /// <param name="rowguid">Initial value of rowguid.</param>
        /// <param name="modifiedDate">Initial value of ModifiedDate.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static SalesOrderDetail CreateSalesOrderDetail(int salesOrderID, int salesOrderDetailID, short orderQty, int productID, decimal unitPrice, decimal unitPriceDiscount, decimal lineTotal, global::System.Guid rowguid, global::System.DateTime modifiedDate)
        {
            SalesOrderDetail salesOrderDetail = new SalesOrderDetail();
            salesOrderDetail.SalesOrderID = salesOrderID;
            salesOrderDetail.SalesOrderDetailID = salesOrderDetailID;
            salesOrderDetail.OrderQty = orderQty;
            salesOrderDetail.ProductID = productID;
            salesOrderDetail.UnitPrice = unitPrice;
            salesOrderDetail.UnitPriceDiscount = unitPriceDiscount;
            salesOrderDetail.LineTotal = lineTotal;
            salesOrderDetail.rowguid = rowguid;
            salesOrderDetail.ModifiedDate = modifiedDate;
            return salesOrderDetail;
        }
        /// <summary>
        /// There are no comments for Property SalesOrderID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SalesOrderID
        {
            get
            {
                return this._SalesOrderID;
            }
            set
            {
                this.OnSalesOrderIDChanging(value);
                this._SalesOrderID = value;
                this.OnSalesOrderIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SalesOrderID;
        partial void OnSalesOrderIDChanging(int value);
        partial void OnSalesOrderIDChanged();
        /// <summary>
        /// There are no comments for Property SalesOrderDetailID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SalesOrderDetailID
        {
            get
            {
                return this._SalesOrderDetailID;
            }
            set
            {
                this.OnSalesOrderDetailIDChanging(value);
                this._SalesOrderDetailID = value;
                this.OnSalesOrderDetailIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SalesOrderDetailID;
        partial void OnSalesOrderDetailIDChanging(int value);
        partial void OnSalesOrderDetailIDChanged();
        /// <summary>
        /// There are no comments for Property OrderQty in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public short OrderQty
        {
            get
            {
                return this._OrderQty;
            }
            set
            {
                this.OnOrderQtyChanging(value);
                this._OrderQty = value;
                this.OnOrderQtyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private short _OrderQty;
        partial void OnOrderQtyChanging(short value);
        partial void OnOrderQtyChanged();
        /// <summary>
        /// There are no comments for Property ProductID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ProductID
        {
            get
            {
                return this._ProductID;
            }
            set
            {
                this.OnProductIDChanging(value);
                this._ProductID = value;
                this.OnProductIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ProductID;
        partial void OnProductIDChanging(int value);
        partial void OnProductIDChanged();
        /// <summary>
        /// There are no comments for Property UnitPrice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal UnitPrice
        {
            get
            {
                return this._UnitPrice;
            }
            set
            {
                this.OnUnitPriceChanging(value);
                this._UnitPrice = value;
                this.OnUnitPriceChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _UnitPrice;
        partial void OnUnitPriceChanging(decimal value);
        partial void OnUnitPriceChanged();
        /// <summary>
        /// There are no comments for Property UnitPriceDiscount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal UnitPriceDiscount
        {
            get
            {
                return this._UnitPriceDiscount;
            }
            set
            {
                this.OnUnitPriceDiscountChanging(value);
                this._UnitPriceDiscount = value;
                this.OnUnitPriceDiscountChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _UnitPriceDiscount;
        partial void OnUnitPriceDiscountChanging(decimal value);
        partial void OnUnitPriceDiscountChanged();
        /// <summary>
        /// There are no comments for Property LineTotal in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal LineTotal
        {
            get
            {
                return this._LineTotal;
            }
            set
            {
                this.OnLineTotalChanging(value);
                this._LineTotal = value;
                this.OnLineTotalChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _LineTotal;
        partial void OnLineTotalChanging(decimal value);
        partial void OnLineTotalChanged();
        /// <summary>
        /// There are no comments for Property rowguid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid rowguid
        {
            get
            {
                return this._rowguid;
            }
            set
            {
                this.OnrowguidChanging(value);
                this._rowguid = value;
                this.OnrowguidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _rowguid;
        partial void OnrowguidChanging(global::System.Guid value);
        partial void OnrowguidChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this._ModifiedDate = value;
                this.OnModifiedDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for SalesOrderHeader in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public SalesOrderHeader SalesOrderHeader
        {
            get
            {
                return this._SalesOrderHeader;
            }
            set
            {
                this._SalesOrderHeader = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private SalesOrderHeader _SalesOrderHeader;
    }
    /// <summary>
    /// There are no comments for AdventureWorksModel.SalesOrderHeader in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SalesOrderID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("SalesOrderID")]
    public partial class SalesOrderHeader
    {
        /// <summary>
        /// Create a new SalesOrderHeader object.
        /// </summary>
        /// <param name="salesOrderID">Initial value of SalesOrderID.</param>
        /// <param name="revisionNumber">Initial value of RevisionNumber.</param>
        /// <param name="orderDate">Initial value of OrderDate.</param>
        /// <param name="dueDate">Initial value of DueDate.</param>
        /// <param name="status">Initial value of Status.</param>
        /// <param name="onlineOrderFlag">Initial value of OnlineOrderFlag.</param>
        /// <param name="salesOrderNumber">Initial value of SalesOrderNumber.</param>
        /// <param name="customerID">Initial value of CustomerID.</param>
        /// <param name="shipMethod">Initial value of ShipMethod.</param>
        /// <param name="subTotal">Initial value of SubTotal.</param>
        /// <param name="taxAmt">Initial value of TaxAmt.</param>
        /// <param name="freight">Initial value of Freight.</param>
        /// <param name="totalDue">Initial value of TotalDue.</param>
        /// <param name="rowguid">Initial value of rowguid.</param>
        /// <param name="modifiedDate">Initial value of ModifiedDate.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static SalesOrderHeader CreateSalesOrderHeader(int salesOrderID, byte revisionNumber, global::System.DateTime orderDate, global::System.DateTime dueDate, byte status, bool onlineOrderFlag, string salesOrderNumber, int customerID, string shipMethod, decimal subTotal, decimal taxAmt, decimal freight, decimal totalDue, global::System.Guid rowguid, global::System.DateTime modifiedDate)
        {
            SalesOrderHeader salesOrderHeader = new SalesOrderHeader();
            salesOrderHeader.SalesOrderID = salesOrderID;
            salesOrderHeader.RevisionNumber = revisionNumber;
            salesOrderHeader.OrderDate = orderDate;
            salesOrderHeader.DueDate = dueDate;
            salesOrderHeader.Status = status;
            salesOrderHeader.OnlineOrderFlag = onlineOrderFlag;
            salesOrderHeader.SalesOrderNumber = salesOrderNumber;
            salesOrderHeader.CustomerID = customerID;
            salesOrderHeader.ShipMethod = shipMethod;
            salesOrderHeader.SubTotal = subTotal;
            salesOrderHeader.TaxAmt = taxAmt;
            salesOrderHeader.Freight = freight;
            salesOrderHeader.TotalDue = totalDue;
            salesOrderHeader.rowguid = rowguid;
            salesOrderHeader.ModifiedDate = modifiedDate;
            return salesOrderHeader;
        }
        /// <summary>
        /// There are no comments for Property SalesOrderID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SalesOrderID
        {
            get
            {
                return this._SalesOrderID;
            }
            set
            {
                this.OnSalesOrderIDChanging(value);
                this._SalesOrderID = value;
                this.OnSalesOrderIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SalesOrderID;
        partial void OnSalesOrderIDChanging(int value);
        partial void OnSalesOrderIDChanged();
        /// <summary>
        /// There are no comments for Property RevisionNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte RevisionNumber
        {
            get
            {
                return this._RevisionNumber;
            }
            set
            {
                this.OnRevisionNumberChanging(value);
                this._RevisionNumber = value;
                this.OnRevisionNumberChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte _RevisionNumber;
        partial void OnRevisionNumberChanging(byte value);
        partial void OnRevisionNumberChanged();
        /// <summary>
        /// There are no comments for Property OrderDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime OrderDate
        {
            get
            {
                return this._OrderDate;
            }
            set
            {
                this.OnOrderDateChanging(value);
                this._OrderDate = value;
                this.OnOrderDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _OrderDate;
        partial void OnOrderDateChanging(global::System.DateTime value);
        partial void OnOrderDateChanged();
        /// <summary>
        /// There are no comments for Property DueDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime DueDate
        {
            get
            {
                return this._DueDate;
            }
            set
            {
                this.OnDueDateChanging(value);
                this._DueDate = value;
                this.OnDueDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _DueDate;
        partial void OnDueDateChanging(global::System.DateTime value);
        partial void OnDueDateChanged();
        /// <summary>
        /// There are no comments for Property ShipDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> ShipDate
        {
            get
            {
                return this._ShipDate;
            }
            set
            {
                this.OnShipDateChanging(value);
                this._ShipDate = value;
                this.OnShipDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _ShipDate;
        partial void OnShipDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnShipDateChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this._Status = value;
                this.OnStatusChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte _Status;
        partial void OnStatusChanging(byte value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property OnlineOrderFlag in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool OnlineOrderFlag
        {
            get
            {
                return this._OnlineOrderFlag;
            }
            set
            {
                this.OnOnlineOrderFlagChanging(value);
                this._OnlineOrderFlag = value;
                this.OnOnlineOrderFlagChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _OnlineOrderFlag;
        partial void OnOnlineOrderFlagChanging(bool value);
        partial void OnOnlineOrderFlagChanged();
        /// <summary>
        /// There are no comments for Property SalesOrderNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SalesOrderNumber
        {
            get
            {
                return this._SalesOrderNumber;
            }
            set
            {
                this.OnSalesOrderNumberChanging(value);
                this._SalesOrderNumber = value;
                this.OnSalesOrderNumberChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SalesOrderNumber;
        partial void OnSalesOrderNumberChanging(string value);
        partial void OnSalesOrderNumberChanged();
        /// <summary>
        /// There are no comments for Property PurchaseOrderNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PurchaseOrderNumber
        {
            get
            {
                return this._PurchaseOrderNumber;
            }
            set
            {
                this.OnPurchaseOrderNumberChanging(value);
                this._PurchaseOrderNumber = value;
                this.OnPurchaseOrderNumberChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PurchaseOrderNumber;
        partial void OnPurchaseOrderNumberChanging(string value);
        partial void OnPurchaseOrderNumberChanged();
        /// <summary>
        /// There are no comments for Property AccountNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AccountNumber
        {
            get
            {
                return this._AccountNumber;
            }
            set
            {
                this.OnAccountNumberChanging(value);
                this._AccountNumber = value;
                this.OnAccountNumberChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AccountNumber;
        partial void OnAccountNumberChanging(string value);
        partial void OnAccountNumberChanged();
        /// <summary>
        /// There are no comments for Property CustomerID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CustomerID
        {
            get
            {
                return this._CustomerID;
            }
            set
            {
                this.OnCustomerIDChanging(value);
                this._CustomerID = value;
                this.OnCustomerIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CustomerID;
        partial void OnCustomerIDChanging(int value);
        partial void OnCustomerIDChanged();
        /// <summary>
        /// There are no comments for Property ShipToAddressID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> ShipToAddressID
        {
            get
            {
                return this._ShipToAddressID;
            }
            set
            {
                this.OnShipToAddressIDChanging(value);
                this._ShipToAddressID = value;
                this.OnShipToAddressIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _ShipToAddressID;
        partial void OnShipToAddressIDChanging(global::System.Nullable<int> value);
        partial void OnShipToAddressIDChanged();
        /// <summary>
        /// There are no comments for Property BillToAddressID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> BillToAddressID
        {
            get
            {
                return this._BillToAddressID;
            }
            set
            {
                this.OnBillToAddressIDChanging(value);
                this._BillToAddressID = value;
                this.OnBillToAddressIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _BillToAddressID;
        partial void OnBillToAddressIDChanging(global::System.Nullable<int> value);
        partial void OnBillToAddressIDChanged();
        /// <summary>
        /// There are no comments for Property ShipMethod in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ShipMethod
        {
            get
            {
                return this._ShipMethod;
            }
            set
            {
                this.OnShipMethodChanging(value);
                this._ShipMethod = value;
                this.OnShipMethodChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ShipMethod;
        partial void OnShipMethodChanging(string value);
        partial void OnShipMethodChanged();
        /// <summary>
        /// There are no comments for Property CreditCardApprovalCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreditCardApprovalCode
        {
            get
            {
                return this._CreditCardApprovalCode;
            }
            set
            {
                this.OnCreditCardApprovalCodeChanging(value);
                this._CreditCardApprovalCode = value;
                this.OnCreditCardApprovalCodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreditCardApprovalCode;
        partial void OnCreditCardApprovalCodeChanging(string value);
        partial void OnCreditCardApprovalCodeChanged();
        /// <summary>
        /// There are no comments for Property SubTotal in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal SubTotal
        {
            get
            {
                return this._SubTotal;
            }
            set
            {
                this.OnSubTotalChanging(value);
                this._SubTotal = value;
                this.OnSubTotalChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _SubTotal;
        partial void OnSubTotalChanging(decimal value);
        partial void OnSubTotalChanged();
        /// <summary>
        /// There are no comments for Property TaxAmt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal TaxAmt
        {
            get
            {
                return this._TaxAmt;
            }
            set
            {
                this.OnTaxAmtChanging(value);
                this._TaxAmt = value;
                this.OnTaxAmtChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _TaxAmt;
        partial void OnTaxAmtChanging(decimal value);
        partial void OnTaxAmtChanged();
        /// <summary>
        /// There are no comments for Property Freight in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal Freight
        {
            get
            {
                return this._Freight;
            }
            set
            {
                this.OnFreightChanging(value);
                this._Freight = value;
                this.OnFreightChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _Freight;
        partial void OnFreightChanging(decimal value);
        partial void OnFreightChanged();
        /// <summary>
        /// There are no comments for Property TotalDue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal TotalDue
        {
            get
            {
                return this._TotalDue;
            }
            set
            {
                this.OnTotalDueChanging(value);
                this._TotalDue = value;
                this.OnTotalDueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _TotalDue;
        partial void OnTotalDueChanging(decimal value);
        partial void OnTotalDueChanged();
        /// <summary>
        /// There are no comments for Property Comment in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Comment
        {
            get
            {
                return this._Comment;
            }
            set
            {
                this.OnCommentChanging(value);
                this._Comment = value;
                this.OnCommentChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Comment;
        partial void OnCommentChanging(string value);
        partial void OnCommentChanged();
        /// <summary>
        /// There are no comments for Property rowguid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid rowguid
        {
            get
            {
                return this._rowguid;
            }
            set
            {
                this.OnrowguidChanging(value);
                this._rowguid = value;
                this.OnrowguidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _rowguid;
        partial void OnrowguidChanging(global::System.Guid value);
        partial void OnrowguidChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this._ModifiedDate = value;
                this.OnModifiedDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for Customer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Customer Customer
        {
            get
            {
                return this._Customer;
            }
            set
            {
                this._Customer = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Customer _Customer;
        /// <summary>
        /// There are no comments for SalesOrderDetails in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<SalesOrderDetail> SalesOrderDetails
        {
            get
            {
                return this._SalesOrderDetails;
            }
            set
            {
                if ((value != null))
                {
                    this._SalesOrderDetails = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<SalesOrderDetail> _SalesOrderDetails = new global::System.Collections.ObjectModel.Collection<SalesOrderDetail>();
    }
}
